### PR TITLE
Improve README.md

### PR DESCRIPTION
**Pull request by Alyetama**
- Some improvements to README.md
- Renames imgs to demo_images
- Added requirements.txt file

I updated the version. You can publish the new version to show the new README on pypi with:

```sh
poetry build
poetry publish
```

### CODE REVIEW

**Comment by pengbo-learn** [comment]
Github email was marked as trash so I missed this one. 
It reads "pengbo-learn closed this 21 hours ago", but I did not see this merge till today.
Yesterday I found some history commits were pushed using root config emails, to remove these commits I finally remove all history commits. Does it has anything to do with this?
Could it be remedied now? @Alyetama

**Comment by Alyetama** [comment]
> Github email was marked as trash so I missed this one. It reads "pengbo-learn closed this 21 hours ago", but I did not see this merge till today. Yesterday I found some history commits were pushed using root config emails, to remove these commits I finally remove all history commits. Does it has anything to do with this? Could it be remedied now? @Alyetama

No, only people with access to the repository can change its history. I don't have access to the repository.  Maybe you have an app installed on github that runs in the background?
You can reopen this pull request, and simply merge.

**Comment by pengbo-learn** [comment]
> > Github email was marked as trash so I missed this one. It reads "pengbo-learn closed this 21 hours ago", but I did not see this merge till today. Yesterday I found some history commits were pushed using root config emails, to remove these commits I finally remove all history commits. Does it has anything to do with this? Could it be remedied now? @Alyetama
> 
> No, only people with access to the repository can change its history. I don't have access to the repository. Maybe you have an app installed on github that runs in the background? You can reopen this pull request, and simply merge.

The closed button is not clickable, neither could I view the modification. It seems the contents of the pull request was deleted along with all the commits history.

**Comment by Alyetama** [comment]
You can fix it with:

```sh
git clone https://github.com/Alyetama/python-color-transfer.git
cd python-color-transfer
git remote add origin git@github.com:pengbo-learn/python-color-transfer.git  # or https://github.com/pengbo-learn/python-color-transfer.git
git push -f
```

**Comment by pengbo-learn** [comment]
> You can fix it with:
> 
> ```shell
> git clone https://github.com/Alyetama/python-color-transfer.git
> cd python-color-transfer
> git remote add origin git@github.com:pengbo-learn/python-color-transfer.git  # or https://github.com/pengbo-learn/python-color-transfer.git
> git push -f
> ```

Pretty README display!
I change demo_images folder back to imgs, since demo.py still refer to imgs.
You are always so nice 😊

**Comment by pengbo-learn** [comment]
> You can fix it with:
> 
> ```shell
> git clone https://github.com/Alyetama/python-color-transfer.git
> cd python-color-transfer
> git remote add origin git@github.com:pengbo-learn/python-color-transfer.git  # or https://github.com/pengbo-learn/python-color-transfer.git
> git push -f
> ```

Bad news, the commits with wrong config emails came back 'c6fdb28'.

**Comment by Alyetama** [comment]
> > You can fix it with:
> > ```shell
> > git clone https://github.com/Alyetama/python-color-transfer.git
> > cd python-color-transfer
> > git remote add origin git@github.com:pengbo-learn/python-color-transfer.git  # or https://github.com/pengbo-learn/python-color-transfer.git
> > git push -f
> > ```
> 
> Bad news, the commits with wrong config emails came back 'c6fdb28'.


The last commit look fine to me.

**Pull request closed without merging**
