### PR TITLE
Add pyproject.toml; add build workflow; update code style to PEP8

### PR DESCRIPTION
**Pull request by Alyetama**
In this pull request:
- I added a `pyproject.toml` to build a package wheel and a github actions workflow that does that automatically.
- Refactored the name of the module in case you plan to publish it on pypi.
- Updated the `.gitignore` file to ignore files that are often ignored in python projects.
- Reformatted the source code to somewhat conform to PEP8.

### CODE REVIEW

**Comment by pengbo-learn** [comment]
> In this pull request:
> 
> * I added a `pyproject.toml` to build a package wheel and a github actions workflow that does that automatically.
> * Refactored the name of the module in case you plan to publish it on pypi.
> * Updated the `.gitignore` file to ignore files that are often ignored in python projects.
> * Reformatted the source code to somewhat conform to PEP8.

what do these two files (pyproject.toml, poetry.yml) do? it's beyond my current knowledge. which keywords may help me search the relevant skills? thanks

**Comment by Alyetama** [comment]
`pyproject.toml` is a package specification file. `Poetry` uses it to build the package wheels. `Poetry.yml` is a GitHub action that builds the package automatically for every push/pull requests, which is useful for testing the build automatically on multiple versions of Python.

To use the files in a meaningful way, I suggest you do the following:

- Install poetry, and sign up to PyPi, then publish the package on PyPi so people can install it with `pip`.

```sh
pip install poetry
```

then:
```
cd python-color-transfer
git pull
poetry build
poetry publish
```

You can learn more here: https://python-poetry.org/

**Comment by pengbo-learn** [comment]
> `pyproject.toml` is a package specification file. `Poetry` uses it to build the package wheels. `Poetry.yml` is a GitHub action that builds the package automatically for every push/pull requests, which is useful for testing the build automatically on multiple versions of Python.
> 
> To use the files in a meaningful way, I suggest you do the following:
> 
> * Install poetry, and sign up to PyPi, then publish the package on PyPi so people can install it with `pip`.
> 
> ```shell
> pip install poetry
> ```
> 
> then:
> 
> ```
> cd python-color-transfer
> git pull
> poetry build
> poetry publish
> ```
> 
> You can learn more here: https://python-poetry.org/

Thank you so much. 
The difficulty annoyed me was that 'poetry publish' won't allow a same version overwrite. Though, I manage to publish with a weird modified version.
I thought releasing a package was a complex job, didn't expect it so convenient
Thanks again!

**Comment by Alyetama** [comment]
The version thing is coming from PyPi not Poetry. PyPi won't allow you to overwrite a version once you publish it to maintain version integrity (i.e., making sure that the same version name has the same wheels for all the people who installed it).

And sure, not a problem! Congrats on releasing your first package! 😸

**Pull request merged**
